// import h1 from './images/h1.jpg'
// import h2 from './images/h2.jpg'
// import h3 from './images/h3.jpg'
// import h4 from './images/h4.jpg'
// import h5 from './images/h5.jpg'
// import h6 from './images/h6.jpg'
// import f1 from './images/f1.jpg'
// import f2 from './images/f2.jpg'
// import f3 from './images/f3.jpeg'
// import f4 from './images/f4.jpg'
// import f6 from './images/f6.jpg'
// import h1 from '../public/images/h1.jpg'

export const arr = [
    {   id:1,
        image:'../public/images/h1.jpg',
        location:"Delhi",
        type:"House",
        BHK:"4BHK",
        price:"34000",
        buy:"Rent",
        name:"Jainam House",
        address:"Near Rajiv Chock 205 A",
        beds:"4",
        bathrooms:"3",
        area:"5×7"
    },
    {   id:2,
        image:'../public/images/f1.jpg',
        location:"Delhi",
        type:"Flat",
        BHK:"2BHK",
        price:"12000",
        buy:"Rent",
        name:"Sky View",
        address:"32 B Mayapuri",
        beds:"2",
        bathrooms:"2",
        area:"3×4"
    },
    {   id:3,
        image:'../public/images/f2.jpg',
        location:"Indore",
        type:"Flat",
        BHK:"1BHK",
        price:"10000",
        buy:"Rent",
        name:"Vishal Residence",
        address:"19 F Silicon City ",
        beds:"1",
        bathrooms:"1",
        area:"3×3"
    },
    {   id:4,
        image:'../public/images/h2.jpg',
        location:"Indore",
        type:"House",
        BHK:"3BHK",
        price:"32000",
        buy:"Rent",
        name:"Mannat",
        address:"208 S Scheme 140",
        beds:"3",
        bathrooms:"3",
        area:"5×7"
    },
    {   id:5,
        image:'../public/images/h3.jpg',
        location:"Banglore",
        type:"House",
        BHK:"4BHK",
        price:"52000",
        buy:"Rent",
        name:"The Gables",
        address:"305 A Near Gandhi Swaure",
        beds:"4",
        bathrooms:"3",
        area:"8×7"
    },
    {   id:6,
        image:'../public/images/f3.jpeg',
        location:"Banglore",
        type:"flat",
        BHK:"3BHK",
        price:"32000",
        buy:"Rent",
        name:"sparten land",
        address:"304 C House Boaard Office Colony",
        beds:"3",
        bathrooms:"3",
        area:"5×8"
    },
    {   id:7,
        image:'../public/images/h4.jpg',
        location:"pune",
        type:"flat",
        BHK:"2BHK",
        price:"33700",
        buy:"Rent",
        name:"blue stone",
        address:"22 D Near Bombay hospital",
        beds:"2",
        bathrooms:"1",
        area:"3×9"
    },
    {   id:8,
        image:'../public/images/f4.jpg',
        location:"Mumbai",
        type:"flat",
        BHK:"2BHK",
        price:"29700",
        buy:"Rent",
        name:"oregano height",
        address:"12 E Newyork City",
        beds:"2",
        bathrooms:"1",
        area:"5×4"
    },
    {   id:9,
        image:'../public/images/h5.jpg',
        location:"Indore",
        type:"house",
        beds:"2BHK",
        price:"13900",
        BHK:"Rent",
        name:"Hedera House",
        address:"20 F Geeta Bahwan Sqauare",
        beds:"2",
        bathrooms:"2",
        area:"4×9"
    },
    {   id:10,
        image:'../public/images/f6.jpg',
        location:"Indore",
        type:"flat",
        BHK:"1BHK",
        price:"8900",
        buy:"Rent",
        name:"escoraa avenue",
        address:"34 C Palsia Square",
        beds:"1",
        bathrooms:"1",
        area:"5×7"
    },
    {   id:11,
        image:'../public/images/h6.jpg',
        location:"Indore",
        type:"house",
        BHK:"4BHK",
        price:"26900",
        buy:"Rent",
        name:"Holmeswoodt",
        address:"303 A Vijay Nagar",
        beds:"4",
        bathrooms:"3",
        area:"10×7"
    },
]